import type { ProductsData } from './types';

export const SEED_DATA: ProductsData = {
  categories: [
    { slug: 'zelte', name: 'Zelte & Zubehör', order: 0 },
    { slug: 'tische', name: 'Tische & Stühle', order: 1 },
    { slug: 'beleuchtung', name: 'Beleuchtung & Heizung', order: 2 },
    { slug: 'deko', name: 'Dekoartikel & Spiele', order: 3 },
  ],
  products: [
    {
      id: 'faltzelt-3x3',
      category: 'zelte',
      images: ['/images/products/faltzelt-3x3.jpg'],
      image: '/images/products/faltzelt-3x3.jpg',
      name: 'Faltzelt 3×3 m',
      description: 'Platz für bis zu 12 Personen',
      price: '25 €',
      priceUnit: 'pro Miete (bis zu 5 Tage)',
      youtubeLink: 'https://youtu.be/3CsNV8e3tOw',
      tags: [],
      visible: true,
      pinned: false,
      quantityOk: 1,
      quantityRepair: 0,
      quantityBroken: 0,
    },
    {
      id: 'faltzelt-3x6',
      category: 'zelte',
      images: ['/images/products/faltzelt-3x6.jpg'],
      image: '/images/products/faltzelt-3x6.jpg',
      name: 'Faltzelt 3×6 m',
      description: 'Platz für bis zu 24 Personen',
      price: '42 €',
      priceUnit: 'pro Miete (bis zu 5 Tage)',
      tags: [],
      visible: true,
      pinned: false,
      quantityOk: 1,
      quantityRepair: 0,
      quantityBroken: 0,
    },
    {
      id: 'seitenwand-fenster',
      category: 'zelte',
      images: ['/images/products/seitenwand-fenster.jpg'],
      image: '/images/products/seitenwand-fenster.jpg',
      name: 'Seitenwand mit Fenster',
      price: '2 €',
      priceUnit: 'pro Miete (bis zu 5 Tage)',
      tags: [],
      visible: true,
      pinned: false,
      quantityOk: 1,
      quantityRepair: 0,
      quantityBroken: 0,
    },
    {
      id: 'seitenwand-reissverschluss',
      category: 'zelte',
      images: [
        '/images/products/seitenwand-reissverschluss-geschlossen.jpg',
        '/images/products/seitenwand-reissverschluss-offen.jpg',
      ],
      image: '/images/products/seitenwand-reissverschluss-geschlossen.jpg',
      name: 'Seitenwand mit Reißverschluss',
      price: '2 €',
      priceUnit: 'pro Miete (bis zu 5 Tage)',
      tags: [],
      visible: true,
      pinned: false,
      quantityOk: 1,
      quantityRepair: 0,
      quantityBroken: 0,
    },
    {
      id: 'gewicht-metallplatte',
      category: 'zelte',
      images: ['/images/products/gewicht-metallplatte.jpg'],
      image: '/images/products/gewicht-metallplatte.jpg',
      name: 'Gewicht — Metallplatte',
      price: '2 €',
      priceUnit: 'pro Miete (bis zu 5 Tage)',
      tags: [],
      visible: true,
      pinned: false,
      quantityOk: 1,
      quantityRepair: 0,
      quantityBroken: 0,
    },
    {
      id: 'gewicht-wasser',
      category: 'zelte',
      images: ['/images/products/gewicht-wasser.jpg'],
      image: '/images/products/gewicht-wasser.jpg',
      name: 'Gewicht — Wasser',
      price: '2 €',
      priceUnit: 'pro Miete (bis zu 5 Tage)',
      tags: [],
      visible: true,
      pinned: false,
      quantityOk: 1,
      quantityRepair: 0,
      quantityBroken: 0,
    },
    {
      id: 'bodenanker-ratsche',
      category: 'zelte',
      images: [
        '/images/products/bodenanker.jpg',
        '/images/products/ratsche-spanngurt.jpg',
      ],
      image: '/images/products/bodenanker.jpg',
      name: 'Bodenanker & Ratsche',
      price: '4 €',
      priceUnit: 'pro Miete (bis zu 5 Tage)',
      tags: [],
      visible: true,
      pinned: false,
      quantityOk: 1,
      quantityRepair: 0,
      quantityBroken: 0,
    },
    {
      id: 'tisch',
      category: 'tische',
      images: ['/images/products/klapptisch.jpg'],
      image: '/images/products/klapptisch.jpg',
      name: 'Tisch',
      description: 'Klappbar · 182 × 74 × 74 cm · Platz für bis zu 8 Personen',
      price: '12 €',
      priceUnit: 'pro Miete (bis zu 5 Tage)',
      tags: [],
      visible: true,
      pinned: false,
      quantityOk: 1,
      quantityRepair: 0,
      quantityBroken: 0,
    },
    {
      id: 'stuhl',
      category: 'tische',
      images: ['/images/products/klappstuhl.jpg'],
      image: '/images/products/klappstuhl.jpg',
      name: 'Stuhl',
      price: '2,50 €',
      priceUnit: 'pro Miete (bis zu 5 Tage)',
      tags: [],
      visible: true,
      pinned: false,
      quantityOk: 1,
      quantityRepair: 0,
      quantityBroken: 0,
    },
    {
      id: 'tischdecke',
      category: 'tische',
      images: ['/images/products/tischdecke.jpg'],
      image: '/images/products/tischdecke.jpg',
      name: 'Tischdecke',
      description: 'inkl. Reinigung',
      price: '4,50 €',
      priceUnit: 'pro Miete (bis zu 5 Tage)',
      tags: [],
      visible: true,
      pinned: false,
      quantityOk: 1,
      quantityRepair: 0,
      quantityBroken: 0,
    },
    {
      id: 'lichterkette',
      category: 'beleuchtung',
      images: ['/images/products/lichterkette.jpg'],
      image: '/images/products/lichterkette.jpg',
      name: 'Lichterkette 18 m',
      price: '8 €',
      priceUnit: 'pro Miete (bis zu 5 Tage)',
      tags: [],
      visible: true,
      pinned: false,
      quantityOk: 1,
      quantityRepair: 0,
      quantityBroken: 0,
    },
    {
      id: 'heizstrahler',
      category: 'beleuchtung',
      images: ['/images/products/heizstrahler.jpg'],
      image: '/images/products/heizstrahler.jpg',
      name: 'Heizstrahler',
      description: 'ohne Gasflasche; 11 kg Gas reichen für ca. 8 Std.',
      price: '25 €',
      priceUnit: 'pro Miete (bis zu 5 Tage)',
      tags: [],
      visible: true,
      pinned: false,
      quantityOk: 1,
      quantityRepair: 0,
      quantityBroken: 0,
    },
    {
      id: 'gasflasche',
      category: 'beleuchtung',
      images: ['/images/products/gasflasche.jpg'],
      image: '/images/products/gasflasche.jpg',
      name: 'Gasflasche',
      price: '3 €',
      priceUnit: 'pro kg',
      tags: [],
      visible: true,
      pinned: false,
      quantityOk: 1,
      quantityRepair: 0,
      quantityBroken: 0,
    },
    {
      id: 'hochzeitsbogen',
      category: 'deko',
      images: [
        '/images/products/hochzeitsbogen.jpg',
        '/images/products/hochzeitsbogen-masse.jpg',
      ],
      image: '/images/products/hochzeitsbogen.jpg',
      name: 'Hochzeitsbogen inkl. Abdeckung',
      description: 'Breite × Höhe: 1,2 m × 2,2 m',
      price: '13 €',
      priceUnit: 'pro Miete (bis zu 5 Tage)',
      tags: [],
      visible: true,
      pinned: false,
      quantityOk: 1,
      quantityRepair: 0,
      quantityBroken: 0,
    },
    {
      id: 'riesenjenga',
      category: 'deko',
      images: ['/images/products/riesenjenga.jpg'],
      image: '/images/products/riesenjenga.jpg',
      name: 'Riesenjenga',
      description: 'bis 1,50 m hoch stapelbar',
      price: '15,50 €',
      priceUnit: 'pro Miete (bis zu 5 Tage)',
      tags: [],
      visible: true,
      pinned: false,
      quantityOk: 1,
      quantityRepair: 0,
      quantityBroken: 0,
    },
  ],
  promotions: [],
  settings: {
    phone: '',
    whatsapp: '',
    email: '',
    instagram: '',
  },
};
